### ISSUE TITLE
data

### ISSUE THREAD

**Issue by ymxka** [SteamerLee/MASA#1]
Hi,
Thank you for open-sourcing your code, but I couldn't run it with cryptocurrency data. 
Could you provide me with your data?

**Comment by SteamerLee** [comment]
Two samples of the dataset have been uploaded to "./data" for your reference. You may replace them by your own data. Due to the data policy in the source platform, we may not be able to share all the datasets.  Besides, please carefully check and modify the config.py file accordingly when applied to other markets. Thank you!
