### ISSUE TITLE
Use of the SP500 data 

### ISSUE THREAD

**Issue by lanqian110** [SteamerLee/MASA#2]
Hi, thanks for your sharing.
I experimented with your sp500 data from the last repository, but in the "data = self.process_finedata(data=data)" have an error.
![Uploading 屏幕截图 2024-03-18 213717.png…]()

Could you please help me?

**Comment by lanqian110** [comment]
ValueError: [Train, fine market] | ref date number: 1052, extract date number: 1047 
missing dates in ref: {Timestamp('2014-07-02 00:00:00'), Timestamp('2014-07-01 00:00:00'), Timestamp('2014-07-08 00:00:00'), Timestamp('2014-07-07 00:00:00'), Timestamp('2014-07-03 00:00:00')}
missing dates in extraction: set()

**Comment by SteamerLee** [comment]
The error shows that the trading dates of market data do not match that of stock data. From your provided information, please try to set the start date of training to be one month after the start date of the dataset, which depends on the historical window size of the financial indicators defined in the config.py for calculating the available features (The dates that do not have enough historical data to calculate the features will be removed, so that's why the dates from 2014-07-01 to 2014-07-08 are filtered). In your case, you may try to set the start date of training on or after 2014-08-01 00:00:00. Thank you for your kind attention!
