### ISSUE TITLE
featGem ERROR

### ISSUE THREAD

**Issue by lrhgogogo** [SteamerLee/MASA#6]
![image](https://github.com/user-attachments/assets/4febb79a-14ea-4078-93e5-3cc5c50afbb6)

fsd_date_lst begin with 2013-09-03, while daily_date_lst begin with 2013-09-10 case an "inner merge" in scale_feat() before, how to deal with it?

**Comment by SteamerLee** [comment]
Hi, please ensure that the two dataframes have the data in the same date list. Besides, if you set the start date of training on '2013-09-03', please include more two-month data (e.g., 2013-07-01 to 2013-09-03) as the observation period before the start date for extracting the features; Otherwise, it may miss some features on 2013-09-03. The observation period can be modified in the configuration file.

Thank you!
