### ISSUE TITLE
Data Issue

### ISSUE THREAD

**Issue by lrhgogogo** [SteamerLee/MASA#7]
![1729221083789(1)](https://github.com/user-attachments/assets/3c267a0d-04ed-4bb0-b763-4a75e052c42a)

I find that in SAMPLE_DJIA_10_1d.csv, most 'close' < 'low', so is the stock data i got from Yuhoo. While when it comes to DJIA_index data, there is no such situation. Why is that? Is that normal？

**Comment by SteamerLee** [comment]
The provided file is the sample data before preprocessing. The close price in the file is the adjusted price while the high/low/open prices are the raw prices. Threfore, you may find that in Yahoo Finance sometimes the adjusted close price of stocks will be lower than the low price in a few years ago, while the index data usually do not need to be adjusted. Here are some possible solutions:
1) Use the daily changes of those features (.e.g, +1.2%) rather than the actual values of those features to reduce the possible impacts. The movement of the price is much important for the model to learn patterns.
2) Try to collect data in a more professional platform.
3) Adjust all prices before using them based on the same adjustment rules.

Thank you!

**Comment by lrhgogogo** [comment]
Thank you very much for your enthusiastic reply！May I ask which one did you use in the experiment, the adjusted price or the original price ?

**Comment by SteamerLee** [comment]
> enthusiastic

Adjusted price. Thank you!

**Comment by SteamerLee** [comment]
> Thank you very much for your enthusiastic reply！May I ask which one did you use in the experiment, the adjusted price or the original price ?

Adjusted price. Thank you!
